### ISSUE TITLE
licença

### ISSUE THREAD

**Issue by pangelo** [altLab/LabBlueprints#9]
Era boa ideia definir qual a licença sob a qual estão os materiais do repositório. A minha sugestão é a [Creative Commons Attribution-ShareAlike 4.0 International](http://creativecommons.org/licenses/by-sa/4.0/)

**Comment by dinix64** [comment]
Thanks pelas dicas
Que achas de colocar estas practicas no documents?

**Comment by pangelo** [comment]
Boa ideia. Criei um draft no documenta: http://altlab.org/d/s/processos/

Dá uma olhada

**Comment by dinix64** [comment]
https://creativecommons.org/licenses/by-sa/4.0/
o novo site da licença
